server:
  port: 8081
  
app:
    name: "Spring Profiles Demo"
    description: "Welcome to ${app.name}"

my:
    greeting: "Hello dear, Welcome"
    list:
        values : "one, two, theree"
    
db:
    connection: "{connectionStting:'http://localhost',userName: 'foo', password: 'pass'}"
    host: 127.0.0.1
    port: 1200
    
spring:
  profiles:
    active:
    - test
